# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "C:\Users\Baptiste\Documents\Projet M1\System and network\Projet"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "C:\Users\Baptiste\Documents\Projet M1\System and network\Projet\build1"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "C:\Users\Baptiste\Documents\Projet M1\System and network\Projet\build1\CMakeFiles" "C:\Users\Baptiste\Documents\Projet M1\System and network\Projet\build1\CMakeFiles\progress.marks"
	$(MAKE) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "C:\Users\Baptiste\Documents\Projet M1\System and network\Projet\build1\CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Battleship

# Build rule for target.
Battleship: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 Battleship
.PHONY : Battleship

# fast build rule for target.
Battleship/fast:
	$(MAKE) -f CMakeFiles\Battleship.dir\build.make CMakeFiles/Battleship.dir/build
.PHONY : Battleship/fast

Board/Board.obj: Board/Board.c.obj

.PHONY : Board/Board.obj

# target to build an object file
Board/Board.c.obj:
	$(MAKE) -f CMakeFiles\Battleship.dir\build.make CMakeFiles/Battleship.dir/Board/Board.c.obj
.PHONY : Board/Board.c.obj

Board/Board.i: Board/Board.c.i

.PHONY : Board/Board.i

# target to preprocess a source file
Board/Board.c.i:
	$(MAKE) -f CMakeFiles\Battleship.dir\build.make CMakeFiles/Battleship.dir/Board/Board.c.i
.PHONY : Board/Board.c.i

Board/Board.s: Board/Board.c.s

.PHONY : Board/Board.s

# target to generate assembly for a file
Board/Board.c.s:
	$(MAKE) -f CMakeFiles\Battleship.dir\build.make CMakeFiles/Battleship.dir/Board/Board.c.s
.PHONY : Board/Board.c.s

Game/Game.obj: Game/Game.c.obj

.PHONY : Game/Game.obj

# target to build an object file
Game/Game.c.obj:
	$(MAKE) -f CMakeFiles\Battleship.dir\build.make CMakeFiles/Battleship.dir/Game/Game.c.obj
.PHONY : Game/Game.c.obj

Game/Game.i: Game/Game.c.i

.PHONY : Game/Game.i

# target to preprocess a source file
Game/Game.c.i:
	$(MAKE) -f CMakeFiles\Battleship.dir\build.make CMakeFiles/Battleship.dir/Game/Game.c.i
.PHONY : Game/Game.c.i

Game/Game.s: Game/Game.c.s

.PHONY : Game/Game.s

# target to generate assembly for a file
Game/Game.c.s:
	$(MAKE) -f CMakeFiles\Battleship.dir\build.make CMakeFiles/Battleship.dir/Game/Game.c.s
.PHONY : Game/Game.c.s

IA/IA.obj: IA/IA.c.obj

.PHONY : IA/IA.obj

# target to build an object file
IA/IA.c.obj:
	$(MAKE) -f CMakeFiles\Battleship.dir\build.make CMakeFiles/Battleship.dir/IA/IA.c.obj
.PHONY : IA/IA.c.obj

IA/IA.i: IA/IA.c.i

.PHONY : IA/IA.i

# target to preprocess a source file
IA/IA.c.i:
	$(MAKE) -f CMakeFiles\Battleship.dir\build.make CMakeFiles/Battleship.dir/IA/IA.c.i
.PHONY : IA/IA.c.i

IA/IA.s: IA/IA.c.s

.PHONY : IA/IA.s

# target to generate assembly for a file
IA/IA.c.s:
	$(MAKE) -f CMakeFiles\Battleship.dir\build.make CMakeFiles/Battleship.dir/IA/IA.c.s
.PHONY : IA/IA.c.s

Ship/Ship.obj: Ship/Ship.c.obj

.PHONY : Ship/Ship.obj

# target to build an object file
Ship/Ship.c.obj:
	$(MAKE) -f CMakeFiles\Battleship.dir\build.make CMakeFiles/Battleship.dir/Ship/Ship.c.obj
.PHONY : Ship/Ship.c.obj

Ship/Ship.i: Ship/Ship.c.i

.PHONY : Ship/Ship.i

# target to preprocess a source file
Ship/Ship.c.i:
	$(MAKE) -f CMakeFiles\Battleship.dir\build.make CMakeFiles/Battleship.dir/Ship/Ship.c.i
.PHONY : Ship/Ship.c.i

Ship/Ship.s: Ship/Ship.c.s

.PHONY : Ship/Ship.s

# target to generate assembly for a file
Ship/Ship.c.s:
	$(MAKE) -f CMakeFiles\Battleship.dir\build.make CMakeFiles/Battleship.dir/Ship/Ship.c.s
.PHONY : Ship/Ship.c.s

fct/fct.obj: fct/fct.c.obj

.PHONY : fct/fct.obj

# target to build an object file
fct/fct.c.obj:
	$(MAKE) -f CMakeFiles\Battleship.dir\build.make CMakeFiles/Battleship.dir/fct/fct.c.obj
.PHONY : fct/fct.c.obj

fct/fct.i: fct/fct.c.i

.PHONY : fct/fct.i

# target to preprocess a source file
fct/fct.c.i:
	$(MAKE) -f CMakeFiles\Battleship.dir\build.make CMakeFiles/Battleship.dir/fct/fct.c.i
.PHONY : fct/fct.c.i

fct/fct.s: fct/fct.c.s

.PHONY : fct/fct.s

# target to generate assembly for a file
fct/fct.c.s:
	$(MAKE) -f CMakeFiles\Battleship.dir\build.make CMakeFiles/Battleship.dir/fct/fct.c.s
.PHONY : fct/fct.c.s

main.obj: main.c.obj

.PHONY : main.obj

# target to build an object file
main.c.obj:
	$(MAKE) -f CMakeFiles\Battleship.dir\build.make CMakeFiles/Battleship.dir/main.c.obj
.PHONY : main.c.obj

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles\Battleship.dir\build.make CMakeFiles/Battleship.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles\Battleship.dir\build.make CMakeFiles/Battleship.dir/main.c.s
.PHONY : main.c.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... rebuild_cache
	@echo ... Battleship
	@echo ... edit_cache
	@echo ... Board/Board.obj
	@echo ... Board/Board.i
	@echo ... Board/Board.s
	@echo ... Game/Game.obj
	@echo ... Game/Game.i
	@echo ... Game/Game.s
	@echo ... IA/IA.obj
	@echo ... IA/IA.i
	@echo ... IA/IA.s
	@echo ... Ship/Ship.obj
	@echo ... Ship/Ship.i
	@echo ... Ship/Ship.s
	@echo ... fct/fct.obj
	@echo ... fct/fct.i
	@echo ... fct/fct.s
	@echo ... main.obj
	@echo ... main.i
	@echo ... main.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

